# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d22f2e7a0c4f856cab542524f6d515daa62e748b1cedee46a515a0d5c74c5e9109697d04b8e7db6a712c0747cc8a5ebf975483a3318913b365a20eb21d72aa26

test:
  secret_key_base: 527d6b179674ef27f6cfd51d49fc1802e97477cdf7a6b825c9de19fa2454c50a02c55b58d323470ace43ab54d7001aca58c0942877a561c83c516b952ad58645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
